# Generated by Django 3.1.2 on 2020-10-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20201031_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
