# Generated by Django 3.1.2 on 2020-10-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20201031_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='catName',
            new_name='name',
        ),
    ]
