# Generated by Django 3.1.2 on 2020-11-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20201031_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
